# Generated by Django 5.2.12 on 2026-03-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cor',
        ),
    ]
