# Generated by Django 5.2.12 on 2026-03-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cor',
            name='nome',
            field=models.CharField(max_length=40),
        ),
    ]
